### ISSUE TITLE
errors esp32 python

### ISSUE THREAD

**Issue by exrector** [arduino/Arduino#10723]
Traceback (most recent call last):
  File "esptool.py", line 57, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports.py", line 29, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_posix.py", line 31, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_osx.py", line 32, in <module>
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
Failed to execute script esptool
exit status 255
/private/var/folders/vv/rxlmj03s5t91qb238wqsshd40000gn/T/AppTranslocation/EFB782B4-05EC-4B07-A1E5-BF6108000DCA/d/Arduino.app/Contents/Java/arduino-builder возвратил 255
Ошибка компиляции для платы ESP32 Dev Module.

21:06:34.971 -> ⸮⸮p⸮⸮"}⸮⸮⸮⸮0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
21:06:34.971 -> mode:DIO, clock div:1
21:06:34.971 -> load:0x3fff0018,len:4
21:06:34.971 -> load:0x3fff001c,len:1216
21:06:34.971 -> ho 0 tail 12 room 4
21:06:34.971 -> load:0x40078000,len:9720
21:06:34.971 -> ho 0 tail 12 room 4
21:06:34.971 -> load:0x40080400,len:6352
21:06:34.971 -> entry 0x400806b8
21:06:36.511 -> ESP32 Chip ID = 1CEA5EBF713C
21:06:39.497 -> ESP32 Chip ID = 1CEA5EBF713C
21:06:42.515 -> ESP32 Chip ID = 1CEA5EBF713C
21:06:45.515 -> ESP32 Chip ID = 1CEA5EBF713C

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post all the relevant information, including your full error output using code tags (`</>` button on the toolbar).
