### ISSUE TITLE
[Arduino website][solved] Arduino IDE cannot download json files due to CloudFlare 5 seconds shield

### ISSUE THREAD

**Issue by MercuryOoO** [arduino/Arduino#10924]
I could access json files with browser but couldn't download json files by Arduino IDE, How to solve this problem?

Debug info:
> 2020-11-05T18:31:04.481Z INFO c.a.u.n.HttpConnectionManager:157 [Timer-0] Request complete URL="https://downloads.arduino.cc/libraries/library_index.json", method=GET, response code=503, request id=DDD1B974AB3B4196, headers={Transfer-Encoding=[chunked], null=[HTTP/1.1 503 Service Temporarily Unavailable], CF-RAY=[5ed8a648dc4e361a-LAX], Server=[cloudflare], Connection=[close], Date=[Thu, 05 Nov 2020 18:31:03 GMT], X-Frame-Options=[SAMEORIGIN], Cache-Control=[private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0], Set-Cookie=[__cfduid=dea718b76a51fabb01b182eec109c261e1604601063; expires=Sat, 05-Dec-20 18:31:03 GMT; path=/; domain=.arduino.cc; HttpOnly; SameSite=Lax], Expires=[Thu, 01 Jan 1970 00:00:01 GMT], Expect-CT=[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"], cf-request-id=[063b4641840000361ab9a2c000000001], Content-Type=[text/html; charset=UTF-8]}
> 2020-11-05T18:31:04.980Z ERROR c.a.u.n.FileDownloader:199 [Timer-0] The request stop
> java.io.IOException: Received invalid http status code from server: 503
>         at cc.arduino.utils.network.FileDownloader.openConnectionAndFillTheFile(FileDownloader.java:239) ~[arduino-core.jar:?]
>         at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:182) [arduino-core.jar:?]
>         at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:129) [arduino-core.jar:?]
>         at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:147) [arduino-core.jar:?]
>         at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:130) [arduino-core.jar:?]
>         at cc.arduino.contributions.JsonDownloader.download(JsonDownloader.java:49) [arduino-core.jar:?]
>         at cc.arduino.contributions.GZippedJsonDownloader.download(GZippedJsonDownloader.java:66) [arduino-core.jar:?]
>         at cc.arduino.contributions.libraries.LibraryInstaller.updateIndex(LibraryInstaller.java:84) [arduino-core.jar:?]
>         at cc.arduino.contributions.ContributionsSelfCheck.updateLibrariesIndex(ContributionsSelfCheck.java:204) [pde.jar:?]
>         at cc.arduino.contributions.ContributionsSelfCheck.run(ContributionsSelfCheck.java:76) [pde.jar:?]
>         at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_191]
>         at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_191]
>

**Comment by MercuryOoO** [comment]
Thank you, the problem seems solved.
