### ISSUE TITLE
Arduino ide 1.8.16 not opening in windows 10

### ISSUE THREAD

**Issue by whitedot00** [arduino/Arduino#11696]
i am getting this error when i run arduino_debug.exe in cmd
 
```
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=1e6f5c3,component=StatusLogger
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=1e6f5c3,component=ContextSelector
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=1e6f5c3,component=Loggers,name=
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=1e6f5c3,component=Appenders,name=Console
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=1e6f5c3,component=Appenders,name=RollingFile
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
TRACE StatusLogger Using DummyNanoClock for nanosecond timestamps.
DEBUG StatusLogger Reconfiguration complete for context[name=1e6f5c3] at URI jar:file:/C:/Program%20Files%20(x86)/Arduino/lib/pde.jar!/log4j2.xml (org.apache.logging.log4j.core.LoggerContext@1a8d91c) with optional ClassLoader: null
DEBUG StatusLogger Shutdown hook enabled. Registering a new one.
DEBUG StatusLogger LoggerContext[name=1e6f5c3, org.apache.logging.log4j.core.LoggerContext@1a8d91c] started OK.
Preparing boards...
java.io.IOException: The cloud file provider is not running
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at processing.app.legacy.PApplet.loadStrings(PApplet.java:249)
        at processing.app.helpers.PreferencesMap.load(PreferencesMap.java:100)
        at processing.app.helpers.PreferencesMap.load(PreferencesMap.java:74)
        at processing.app.packages.UserLibrary.create(UserLibrary.java:77)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanLibrary(LibrariesIndexer.java:226)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanInstalledLibraries(LibrariesIndexer.java:203)
        at cc.arduino.contributions.libraries.LibrariesIndexer.rescanLibraries(LibrariesIndexer.java:163)
        at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:681)
        at processing.app.Base.onBoardOrPortChange(Base.java:1345)
        at processing.app.Base$11.actionPerformed(Base.java:1578)
        at processing.app.Base.rebuildBoardsMenu(Base.java:1550)
        at processing.app.Base.<init>(Base.java:285)
        at processing.app.Base.main(Base.java:150)
java.lang.NullPointerException
        at processing.app.helpers.PreferencesMap.load(PreferencesMap.java:101)
        at processing.app.helpers.PreferencesMap.load(PreferencesMap.java:74)
        at processing.app.packages.UserLibrary.create(UserLibrary.java:77)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanLibrary(LibrariesIndexer.java:226)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanInstalledLibraries(LibrariesIndexer.java:203)
        at cc.arduino.contributions.libraries.LibrariesIndexer.rescanLibraries(LibrariesIndexer.java:163)
        at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:681)
        at processing.app.Base.onBoardOrPortChange(Base.java:1345)
        at processing.app.Base$11.actionPerformed(Base.java:1578)
        at processing.app.Base.rebuildBoardsMenu(Base.java:1550)
        at processing.app.Base.<init>(Base.java:285)
        at processing.app.Base.main(Base.java:150)
DEBUG StatusLogger Stopping LoggerContext[name=1e6f5c3, org.apache.logging.log4j.core.LoggerContext@1a8d91c]
DEBUG StatusLogger Stopping LoggerContext[name=1e6f5c3, org.apache.logging.log4j.core.LoggerContext@1a8d91c]...
TRACE StatusLogger Unregistering 1 MBeans: [org.apache.logging.log4j2:type=1e6f5c3]
TRACE StatusLogger Unregistering 1 MBeans: [org.apache.logging.log4j2:type=1e6f5c3,component=StatusLogger]
TRACE StatusLogger Unregistering 1 MBeans: [org.apache.logging.log4j2:type=1e6f5c3,component=ContextSelector]
TRACE StatusLogger Unregistering 1 MBeans: [org.apache.logging.log4j2:type=1e6f5c3,component=Loggers,name=]
TRACE StatusLogger Unregistering 2 MBeans: [org.apache.logging.log4j2:type=1e6f5c3,component=Appenders,name=RollingFile, org.apache.logging.log4j2:type=1e6f5c3,component=Appenders,name=Console]
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=1e6f5c3,component=AsyncAppenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=1e6f5c3,component=AsyncLoggerRingBuffer'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=1e6f5c3,component=Loggers,name=*,subtype=RingBuffer'
TRACE StatusLogger Stopping XmlConfiguration[location=jar:file:/C:/Program%20Files%20(x86)/Arduino/lib/pde.jar!/log4j2.xml]...
TRACE StatusLogger XmlConfiguration notified 2 ReliabilityStrategies that config will be stopped.
TRACE StatusLogger XmlConfiguration stopping 1 LoggerConfigs.
TRACE StatusLogger XmlConfiguration stopping root LoggerConfig.
TRACE StatusLogger XmlConfiguration notifying ReliabilityStrategies that appenders will be stopped.
TRACE StatusLogger XmlConfiguration stopping remaining Appenders.
DEBUG StatusLogger Shutting down RollingFileManager C:\Users\Maria Kiran\AppData\Local\Arduino15/logs/application.log
DEBUG StatusLogger Shutting down RollingFileManager C:\Users\Maria Kiran\AppData\Local\Arduino15/logs/application.log
DEBUG StatusLogger All asynchronous threads have terminated
DEBUG StatusLogger RollingFileManager shutdown completed with status true
DEBUG StatusLogger Shut down RollingFileManager C:\Users\Maria Kiran\AppData\Local\Arduino15/logs/application.log, all resources released: true
DEBUG StatusLogger Appender RollingFile stopped with status true
DEBUG StatusLogger Shutting down OutputStreamManager SYSTEM_ERR.false.false
DEBUG StatusLogger Shut down OutputStreamManager SYSTEM_ERR.false.false, all resources released: true
DEBUG StatusLogger Appender Console stopped with status true
TRACE StatusLogger XmlConfiguration stopped 2 remaining Appenders.
TRACE StatusLogger XmlConfiguration cleaning Appenders from 2 LoggerConfigs.
DEBUG StatusLogger Stopped XmlConfiguration[location=jar:file:/C:/Program%20Files%20(x86)/Arduino/lib/pde.jar!/log4j2.xml] OK
DEBUG StatusLogger Stopped LoggerContext[name=1e6f5c3, org.apache.logging.log4j.core.LoggerContext@1a8d91c] with status true
```

i tried reinstalling ide but no use of it

**Comment by per1234** [comment]
Hi @whitedot00 please see https://github.com/arduino/Arduino/issues/11128 and the issue I linked to from https://github.com/arduino/Arduino/issues/11128. That will provide the explanation for this "The cloud file provider is not running" error as well as the fix.
