### ISSUE TITLE
Git build: Exception in thread "MessageSiphon" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jaggzh** [arduino/Arduino#11795]
Working from master in Debian stable, when I upload to a device (tried AVR and non-AVR), I get this error.  (The upload then completes anyway).

```
Exception in thread "MessageSiphon" java.lang.NoSuchMethodError: 'boolean org.apache.commons.lang3.StringUtils.containsAny(java.lang.CharSequence, java.lang.CharSequence[])'
	at cc.arduino.packages.Uploader.message(Uploader.java:178)
	at processing.app.debug.MessageSiphon.run(MessageSiphon.java:96)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by MikeOdyn** [comment]
This error message indicates that there is a problem with the version of the Apache Commons Lang library that is being used. The `StringUtils.containsAny` method appears to be missing or has a different signature than expected.

It is possible that there is a version mismatch between the version of the library being used by the Arduino IDE and the version of the library that is being used by the esptool.py script.

One way to resolve this issue would be to try updating the Arduino IDE and the esptool.py script to the latest versions. If you are using a package manager to install these tools, you may need to update the package repository and then upgrade the packages.

Alternatively, you could try manually specifying the version of the Apache Commons Lang library that should be used by the Arduino IDE and the esptool.py script. This may require modifying the library dependencies in the source code or using a different version of the library.

It is also possible that the error is being caused by some other issue, such as a conflict with another library or a problem with the Java runtime environment. In this case, you may need to further troubleshoot the problem to identify the root cause.
