### ISSUE TITLE
Long string constants trigger Java StackOverflowError

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#1401]
Very long string constants cause a Java exception.  Tested on Linux 64 bit.

Here is a sample program which demonstrates the problem.

http://www.pjrc.com/teensy/beta/long_string_bug.ino

Exception in thread "Thread-2807" java.lang.StackOverflowError
	at java.util.regex.Pattern$Branch.match(Pattern.java:4131)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4185)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4312)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4244)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4095)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3362)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4131)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4185)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4312)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4244)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4095)
        [snip...]

**Comment by ffissore** [comment]
Please give a try to the IDEs linked at the bottom of this email on the dev list
https://groups.google.com/a/arduino.cc/forum/#!msg/developers/4X2T3rCxXWM/YNJl6PZuDucJ
We're testing a new preprocessor and it compiles your sketch just fine.

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available

**Comment by aumberg** [comment]
Still problem in hourly build 1.6.6  (Linux x32 and Windows8 x64)

**Comment by ffissore** [comment]
Fixed by #3779
