### ISSUE TITLE
NullPointerexception unless run as admin

### ISSUE THREAD

**Issue by ejb1123** [arduino/Arduino#1900]
Windows 7
using the debug exe in the nightly build.
When stating the IDE I get this.

Exception in thread "main" java.lang.NullPointerException
        at processing.app.I18n._(I18n.java:56)
        at processing.app.Base.getSettingsFolder(Base.java:1976)
        at processing.app.Base.getSettingsFile(Base.java:1993)
        at processing.app.Preferences.init(Preferences.java:258)
        at processing.app.Base.main(Base.java:143)

**Comment by ffissore** [comment]
@ejb1123 can you give a try to latest hourly build? http://www.arduino.cc/en/Main/Software#hourly
