### ISSUE TITLE
Arduino 1.5.6-r2 for 64 bit Linux --upload and --verify bug

### ISSUE THREAD

**Issue by ruipcunha** [arduino/Arduino#1905]
When I use command line to comile/upload sketch to my arduino Due, I get an error if the sketch has errors. That's not critical if I use terminal because I can always use "CTRL+C" to release window, but I'm using compilation command on Geany and I have to restart the program every time (a little annoying)...

Here is the error:
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at processing.app.syntax.TextAreaPainter.nextTabStop(TextAreaPainter.java:497)
	at javax.swing.text.Utilities.getTabbedTextWidth(Unknown Source)
	at javax.swing.text.Utilities.getTabbedTextWidth(Unknown Source)
	at processing.app.syntax.JEditTextArea._offsetToX(JEditTextArea.java:596)
	at processing.app.syntax.JEditTextArea.scrollTo(JEditTextArea.java:478)
	at processing.app.syntax.JEditTextArea.scrollToCaret(JEditTextArea.java:443)
	at processing.app.syntax.JEditTextArea.select(JEditTextArea.java:1237)
	at processing.app.Editor.statusError(Editor.java:2683)
	at processing.app.Editor$DefaultRunHandler.run(Editor.java:1919)
	at processing.app.Base.<init>(Base.java:442)
	at processing.app.Base.main(Base.java:225)

Continue the good work!

Rui

**Comment by ffissore** [comment]
@ruipcunha is this still true with the latest hourly build? http://www.arduino.cc/en/Main/Software#hourly
