### ISSUE TITLE
Serial Port closes with error when uploading or opening a serial monitor when serial.debug_rate=38400 in ubuntu.

### ISSUE THREAD

**Issue by reconlap** [arduino/Arduino#2034]
If the Serial Port baud rate is set to 38400 on ubuntu ( bug observed in xubuntu 14.04 and linux mint), when Arduino IDE 1.0.5 tries to access the port to upload or open a serial monitor you get an error and the port closes and is no longer accessible. oddly this does not happen if you start Arduino with "sudo arduino". 

This is a tricky bug cause you cannot change the baud rate until after you open a serial monitor, which you cannot do.

I resolved the bug by editing ~.arduino/preferances.txt and changing serial.debug_rate=38400 to serial.debug_rate=9600

error message 
processing.app.SerialException: Error opening serial port '/dev/ttyACM0'.
    at processing.app.Serial.<init>(Serial.java:178)
    at processing.app.Serial.<init>(Serial.java:92)
    at processing.app.SerialMonitor.openSerialPort(SerialMonitor.java:207)
    at processing.app.Editor.handleSerial(Editor.java:2481)
    at processing.app.Editor$17.actionPerformed(Editor.java:665)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: gnu.io.UnsupportedCommOperationException: Invalid Parameter
    at gnu.io.RXTXPort.setSerialPortParams(RXTXPort.java:213)
    at processing.app.Serial.<init>(Serial.java:163)
    ... 42 more

**Comment by skvatboy** [comment]
This problem has been fixed by following the answer given in http://askubuntu.com/a/58122/206687. In short, if you add yourself to the dialout group, the problem should get fixed.

    sudo usermod -a -G dialout $USER

Just logout and log back in again after running this command, and you should be able to access the serial port without any problems.

**Comment by per1234** [comment]
The need to add your user to the `dialout` group is expected and documented in the Arduino IDE installation instructions:
https://www.arduino.cc/en/Guide/Linux#please-read

The fact that the issue only occurred with the 38400 baud setting is odd, but I think we can just safely say that you should always add your user to the `dialout` group, so I don't think it's worth investigating the baud rate specificity you encountered.
