### ISSUE TITLE
Can't build ide-1.5.x-java7 branch with Mac (Apple) Java 1.6.0_65

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#2160]
If I try to build and run "ant run" a fresh clone of the Arduino repository, ide-1.5.x-java7 branch (on Mac OS X 10.9.3 with javac 1.6.0_65), I get the stack trace below. I'm assuming this is because the new appbundler requires Java 7, but it would be good to document this somewhere or provide a workaround for Java 6 -- especially since it's the version that Mac OS X prompts you to install if you try to run Java software.

macosx-build:
    [mkdir] Created dir: /Users/mellis/Desktop/Arduino/build/macosx/work
      [get] Getting: http://downloads.arduino.cc/appbundler-1.0-arduino.jar
      [get] To: /Users/mellis/Desktop/Arduino/build/macosx/appbundler-1.0-arduino.jar

BUILD FAILED
/Users/mellis/Desktop/Arduino/build/build.xml:65: The following error occurred while executing this line:
/Users/mellis/Desktop/Arduino/build/build.xml:212: java.lang.UnsupportedClassVersionError: com/oracle/appbundler/AppBundlerTask : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1136)
	at org.apache.tools.ant.AntClassLoader.getClassFromStream(AntClassLoader.java:1307)
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1362)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1323)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1076)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:579)
	at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:237)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by ffissore** [comment]
After 1.6.0, the code is now on master branch. A recent macosx will be identified as such and therefore ant will build the `-java-latest` version. To force building normal `macosx` version, use `ant -Dplatform=macosx clean dist`

Build instructions will be ported and updated with #2621. Closing
