### ISSUE TITLE
Serial port  not found /dev/ttyACM0 - Linux Mint 17 Qiana

### ISSUE THREAD

**Issue by tr2000** [arduino/Arduino#2209]
Applied latest patch set from Mint and from then on the serial port cannot be found. I've followed previous posts, using each USB port in turn, checked 'groups' membership, and 2 Arduino UNO's, looked at the Windows 8 posts on driver permissions (not directly relevant for Linux), but continue to get the error messages (see below). I've even tried to remove and reinstall Arduino IDE.

I know the serial port is there, because 'chmod 777 /dev/ttyACM0' is successful, and if I send a txt file to that port, the RX LED flashes on the Arduino indicating the virtual port has been created and the Arduino is listening to it. 
I now have NO ability to post sketches to my Arduino UNO's.
Errors from IDE during upload below:

processing.app.SerialException: Error opening serial port '/dev/ttyACM0'.
	at processing.app.Serial.<init>(Serial.java:178)
	at processing.app.Serial.<init>(Serial.java:77)
	at processing.app.debug.Uploader.flushSerialBuffer(Uploader.java:77)
	at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:175)
	at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:67)
	at processing.app.Sketch.upload(Sketch.java:1671)
	at processing.app.Sketch.exportApplet(Sketch.java:1627)
	at processing.app.Sketch.exportApplet(Sketch.java:1599)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2380)
	at java.lang.Thread.run(Thread.java:744)
Caused by: gnu.io.UnsupportedCommOperationException: Invalid Parameter
	at gnu.io.RXTXPort.setSerialPortParams(RXTXPort.java:213)
	at processing.app.Serial.<init>(Serial.java:163)
	... 9 more
processing.app.debug.RunnerException: Error opening serial port '/dev/ttyACM0'.
	at processing.app.debug.Uploader.flushSerialBuffer(Uploader.java:101)
	at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:175)
	at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:67)
	at processing.app.Sketch.upload(Sketch.java:1671)
	at processing.app.Sketch.exportApplet(Sketch.java:1627)
	at processing.app.Sketch.exportApplet(Sketch.java:1599)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2380)
	at java.lang.Thread.run(Thread.java:744)

**Comment by ffissore** [comment]
38400 has been restored with #2485
Download the latest nightly build to try it out http://arduino.cc/en/Main/Software#toc4

**Comment by tr2000** [comment]
Moved to Ubuntu 14.04 LTS - no problem with this on the same hardware.

**Comment by pgorellana** [comment]
Try this please 
sudo chmod a+rw /dev/ttyACM0
sudo usermod -a -G dialout <user>
sudo ln -s  /dev/ttyACM0 /dev/ttyUSB0
change the port name ttyACM0 to ttyUSB0 
done!

**Comment by matthijskooijman** [comment]
@pgorellana, this issue is solved, why are you posting random advice here? Also, the symlink you suggest should never be needed for the Arduino IDE, it should detect both device names equally. Doing `a+rw` opens up the permissions for too much people, so I consider that harmful advice. The `usermod` might make sense, but that depends on the system. Better is to point people at https://www.arduino.cc/en/guide/linux#toc6 instead.
