### ISSUE TITLE
1.6.2 crashes upon startup (Ubuntu 14.10 64 bit)

### ISSUE THREAD

**Issue by mschlenker** [arduino/Arduino#2846]
On my Ubuntu 14.10 64 bit 1.6.2 crashes:

mattias@barium:~$ sudo strace -f -e trace=file -o /tmp/trace.out arduino16 
Error parsing gtk-icon-sizes string: ''
java.lang.UnsatisfiedLinkError: com.sun.jna.Native.pointerSize()I
	at com.sun.jna.Native.pointerSize(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:93)
	at cc.arduino.os.linux.LibCNative.<clinit>(LibCNative.java:38)
	at cc.arduino.os.linux.LinuxFileNativeUtils.<clinit>(LinuxFileNativeUtils.java:36)
	at cc.arduino.os.FileNativeUtils.chmod(FileNativeUtils.java:51)
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:236)
	at processing.app.BaseNoGui.initPackages(BaseNoGui.java:585)
	at processing.app.Base.<init>(Base.java:256)
	at processing.app.Base.guardedMain(Base.java:198)
	at processing.app.Base.main(Base.java:113)

The strace output hints to a problem (incompatibility?) of JNI. With which JDK and JNI was the binary for linux 64 bit built?

Please see: https://gist.github.com/mschlenker/01191f6f5e4e07ada73d

**Comment by mschlenker** [comment]
OK, please close, I found the appropriate thread.

I am waiting for the next nightly or trying to build myself. Unti 1.63 is ready you probably should point linux users to 1.6.1.
