### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 3

### ISSUE THREAD

**Issue by cdoc83** [arduino/Arduino#3632]
Launching the IDE shows the splash screen and immediately crashes without notice.  Running arduino_debug.exe from cmd shows the following:

Loading configuration...
java.lang.ArrayIndexOutOfBoundsException: 3
        at processing.app.windows.RegQueryParser.parse(RegQueryParser.java:29)
        at processing.app.windows.RegQueryParser.<init>(RegQueryParser.java:14)
        at processing.app.windows.Platform.getFolderPathFromRegistry(Platform.java:71)
        at processing.app.windows.Platform.recoverDefaultSketchbookFolder(Platform.java:60)
        at processing.app.windows.Platform.init(Platform.java:51)
        at processing.app.Base.guardedMain(Base.java:153)
        at processing.app.Base.main(Base.java:137)

**Comment by ffissore** [comment]
It's a known bug, already fixed in 98eb1a9ee22f3b346787ff9608ab8fa7a7271e6e, available with the hourly build http://www.arduino.cc/en/Main/Software#hourly
