### ISSUE TITLE
1.6.5 Error downloading board definition

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3861]
I just started the boards manager with 1.6.5 r5 under linux and got this (error listed twice, tried twice)

```
Error downloading https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$3.run(ContributionManagerUI.java:158)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:100)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:279)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:255)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:246)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$3.run(ContributionManagerUI.java:154)
	... 1 more
Caused by: java.io.IOException: Recevied invalid http status code from server: 416
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:160)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:98)
	... 5 more
Could not find boards.txt in /Arduino/sketchbook/hardware/HoodLoader2/examples. Is it pre-1.5?
 Error downloading https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$3.run(ContributionManagerUI.java:158)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:100)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:279)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:255)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:246)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$3.run(ContributionManagerUI.java:154)
	... 1 more
Caused by: java.io.IOException: Recevied invalid http status code from server: 416
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:160)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:98)
	... 5 more
Could not find boards.txt in /Arduino/sketchbook/hardware/HoodLoader2/examples. Is it pre-1.5?
```

Is this intended because I turned on the verbose output?

**Comment by ffissore** [comment]
Delete file `package_optiboot_optiboot-additional_index.json` from `.arduino15` and retry
