### ISSUE TITLE
Export compiled binary for Arduino Zero

### ISSUE THREAD

**Issue by agdl** [arduino/Arduino#3905]
Trying to do it, I get the  following error:
IDE 1.6.6 Ubuntu 14.04
processing.app.debug.RunnerException
	at cc.arduino.Compiler.saveHex(Compiler.java:350)
	at cc.arduino.Compiler.saveHex(Compiler.java:324)
	at cc.arduino.Compiler.build(Compiler.java:145)
	at processing.app.Sketch.build(Sketch.java:1109)
	at processing.app.Sketch.build(Sketch.java:1084)
	at processing.app.Editor$BuildHandler.run(Editor.java:2011)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /tmp/build12ffedaf903ce7236bfd665037f5c01b.tmp/ZERO_factoryTest.ino.with_bootloader.bin
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at cc.arduino.Compiler.saveHex(Compiler.java:348)
	... 6 more

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build. http://www.arduino.cc/en/Main/Software#hourly
