### ISSUE TITLE
Boards Manager error with editor language Chinese(Taiwan)

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4095]
Using Arduino 1.6.7 2015/11/05 10:42 with Windows 7 64 bit
- File > Preferences > Editor language: Chinese(Taiwan)
- Restart IDE
- Tools > Board > Boards Manager... produces `Unmatched braces in the pattern.`

Console error:
```
 Unmatched braces in the pattern.
java.lang.RuntimeException: java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$23(ContributionManagerUI.java:149)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(MessageFormat.java:508)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at processing.app.I18n.format(I18n.java:85)
	at cc.arduino.contributions.DownloadableContributionsDownloader.lambda$download$13(DownloadableContributionsDownloader.java:105)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at cc.arduino.utils.network.FileDownloader.setStatus(FileDownloader.java:111)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:206)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:322)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:298)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:276)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$23(ContributionManagerUI.java:145)
	... 1 more
```
This happens with the File > Preferences > Additional Boards Manager URLs field blank.
The error still occurs when all json files have been deleted from Arduino15 folder.
There is no error when Boards Manager is opened with Editor Language: English, Chinese(China), or Chinese(Taiwan)(Big5).

Originally reported at: http://forum.arduino.cc/index.php?topic=357312.msg2463551#msg2463551

**Comment by ffissore** [comment]
Ah! Found the problem: it was indeed a wrong translation. Placeholder `{1}` was mistyped `{1]`, which broke the formatter. Fixed in next hourly build http://www.arduino.cc/en/Main/Software#hourly
