### ISSUE TITLE
Error downloading http://downloads.arduino.cc/packages/package_index.json

### ISSUE THREAD

**Issue by clivepengelly** [arduino/Arduino#5188]
Hi. I have installed a fresh copy of the IDE but continue to get this error when opening the boards manager. I have followed instructions on the forum to rectify the problem but nothing works.
I am running Windows 10.
I can access this URL from my browser.
I am able to install some of the boards that are listed in the boards manager, but most give errors when trying to install.
![image](https://cloud.githubusercontent.com/assets/16300778/17276253/942285a2-5723-11e6-80f3-965c1f42e815.png)

Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$0(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:330)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:305)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:283)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$0(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.net.SocketException: Address family not supported by protocol family: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:83)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 5 more

**Comment by agdl** [comment]
Hi, If you open the preferences menu, you can navigate to the .Arduino15 folder clicking on the preferences path. Then open the folder staging/packages and try to delete all the archive you have there. Please let me know if the problem persist.

**Comment by clivepengelly** [comment]
Hi.

Thanks for the reply.

Deleted the folder, same problem.

 



 

 



Regards,

Clive Pengelly

+27 82 882 4505

**Comment by agdl** [comment]
Can you please give a try to this?

http://stackoverflow.com/questions/16373906/address-family-not-supported-by-protocol-family-socketexception-on-a-specific/21383865#21383865

**Comment by clivepengelly** [comment]
GENIUS!

 

This worked.

 

I am surprised that many more people do not have this problem. I do not have anything special in my environment.

 

This is what I had to do – nothing else:-

 

1.    Open command prompt (windows start button, type cmd in search)

2.    Click top left of command prompt, click properties, enable quick edit mode

3.    Copy: setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true

4.    Right click on command prompt, should paste

5.    Hit enter. That easy!

 

 

Regards,

Clive Pengelly

+27 82 882 4505

**Comment by cmaglie** [comment]
@clivepengelly 
from the linked article it seems that the problem is caused by a spyware:

>    Try to check whether the spy program called "RelevantKnowledge" is installed. Its
>     uninstallation helped me to solve the problem.

You may probably want to check if you have this program installed too.

BTW happy that you solved it!

**Comment by clivepengelly** [comment]
I do have this relevant knowledge thing running. What is it and where does it come from?

 

I download a lot of development and test software.

 

 



 



 

Regards,

Clive Pengelly

+27 82 882 4505

**Comment by cmaglie** [comment]
It doesn't surely come from Arduino.
Probably you installed it bundled with some other software, without noticing.

From a quick search on google:
http://www.relevantknowledge.com/faq.aspx
http://www.shouldiremoveit.com/RelevantKnowledge-12964-program.aspx

**Comment by sachin1389** [comment]
Please help the problem still exist for me 
i have done 
setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true
Success: specified value was saved
and also checked for the relevant knowledge spy.

still getting error

 Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:330)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:305)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:283)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:126)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:459)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 5 more
 Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:330)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:305)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:283)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:126)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:459)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 5 more
 Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:330)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:305)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:283)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:126)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:459)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 5 more
 Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:151)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:330)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:305)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:283)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$19(ContributionManagerUI.java:147)
	... 1 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:126)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:459)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:170)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 5 more

**Comment by sachin1389** [comment]
Hey Problem solved,I just tried remove as much software which was seeing to be unknown to me
and then deleted the arduino and reinstalled and then restarted my pc . now it is working fine.

**Comment by adam4142** [comment]
Its worked ...........
you r a GENIUS>............

**Comment by ArimoJak7** [comment]
thanks 
it worked

**Comment by paulenuta** [comment]
I had same error, but could not manually open the http://downloads.arduino.cc/packages/package_index.json list and solve the problem be restarting PPOE connection to the ISP.

**Comment by Technocratp** [comment]
it's a problem of Internet connectivity in PC or laptop.

**Comment by bigelite** [comment]
i have this problem too, 
I have followed instructions on the forum to rectify the problem but nothing works.
I am running Windows 10.
I can access this URL from my browser.
I've opened the folder staging/packages and  deleted all the archive that i had.
I've tried this one: setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true

but its still had an error. i don't know what to do!

**Comment by ShotgunBurger** [comment]
@bigelite I have the same problem, Tried everything. Did you end up solving the issue?

**Comment by ShotgunBurger** [comment]
I had this issue - I am running Windows 10, Arduino IDE 1.8.3.
I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true
I tried a fresh install of the Arduino IDE
I tried resetting my PPPoE Connection via my modem to my ISP
I tried using WiFi, Ethernet and tethering to my cell phones ISP via personal hotspot
None of these fixed the problem.

I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"

Now it works fine.

**Comment by mrohner** [comment]
This setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true
results in an error:
ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
Type "SETX /?" for usage.

**Comment by jeanmoretto** [comment]
@ShotgunBurger perfect for me. I just deleted that file and "voilà".
It back to work.

**Comment by hamid1234567** [comment]
I could solved this issue by correcting java configuration and change the proxy seeting of java network to correct solution. try these step in windows
1- search configure java  from start menu 
2- In general tab open network setting and correct it (i changed it to direct connection - no proxy )
arduino work and download rapidly any things

**Comment by friesandacoke** [comment]
@ShotgunBurger That was what I needed. Perfect. Thanks!

To add, most will need to unhide hidden files and folders before they can see the appdata folders.

**Comment by sunnydevtale** [comment]
Hi,

I am also facing the same error while managing the Arduino libraries. I have tried all above solution but this didn't worked for me.

For me, getting this error due to internet connectivity. I have switch to another internet network and tried again and this Works..!. 

Hopefully this issue will resolve for you also.

**Comment by MrJ6** [comment]
ShotgunBurger, thanks man you are a life saver ^^

**Comment by sunnydevtale** [comment]
:) YW..!

**Comment by AlexSwensen** [comment]
I think it might be down today. Tried to access the URL from my phone and home connection. No dice.

**Comment by AlexSwensen** [comment]
And its back.

**Comment by tin345** [comment]
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"

This one worked for me also.... Thanks Much...

**Comment by VaidehiTrivedi** [comment]
Just try doing this 

I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"

and if this doesn't work, refer this link : "https://stackoverflow.com/questions/16373906/address-family-not-supported-by-protocol-family-socketexception-on-a-specific/21383865#21383865"

**Comment by haithamkob** [comment]
it worked for me by deleting  "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"

**Comment by Prateek7805** [comment]
it worked by deleted the Arduino15 folder contents now time to go back

**Comment by pedrohas2000** [comment]
> @clivepengelly
> from the linked article it seems that the problem is caused by a spyware:
> 
> > Try to check whether the spy program called "RelevantKnowledge" is installed. Its
> > uninstallation helped me to solve the problem.
> 
> You may probably want to check if you have this program installed too.
> 
> BTW happy that you solved it!

It`s worked for me!

**Comment by yokozawa766** [comment]
Just copy company's proxy setting to ArduinoIDE>preference>NetworkTab. It works. You can use library manager and board manager.

**Comment by maurodom** [comment]
I tried every fix here with no results.
Afterwards I momentarely disabled my TinyWall firewall and then the "Error downloading http://downloads.arduino.cc/packages/package_index.json" disppeared.
All the boards I needed have been immediately downloaded.
Hope it helps.

**Comment by yokozawa766** [comment]
MR. maurodom,
I write the way to the picture ;
http://yokozawa766.car.coocan.jp/proxy.jpg

**Comment by zexalistic** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3
> I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
> I tried a fresh install of the Arduino IDE
> I tried resetting my PPPoE Connection via my modem to my ISP
> I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
> None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

Thank you very much!!!

**Comment by cooldew2007** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3
> I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
> I tried a fresh install of the Arduino IDE
> I tried resetting my PPPoE Connection via my modem to my ISP
> I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
> None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

This worked for me. Cheers

**Comment by DarkStar18** [comment]
@clivepengelly Wow, open the Command and paste "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true" WORK perfectly. Thank you so much for solving my problem

**Comment by xuanbka1** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3
> I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
> I tried a fresh install of the Arduino IDE
> I tried resetting my PPPoE Connection via my modem to my ISP
> I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
> None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

thanks !! so lady

**Comment by AnnaLobo** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3
> I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
> I tried a fresh install of the Arduino IDE
> I tried resetting my PPPoE Connection via my modem to my ISP
> I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
> None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

thaaaaanks the only thing that worked \o/

**Comment by amrithmmh** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3
> I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
> I tried a fresh install of the Arduino IDE
> I tried resetting my PPPoE Connection via my modem to my ISP
> I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
> None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

this worked for me

**Comment by MattCosturos** [comment]
This issue is still happening!

I had to go to https://downloads.arduino.cc/packages/package_index.json and then download all the certificates.
Then I had to manually import these certs into the cacerts file in the JRE which was installed in the Arduino directory! (not in the global java directory!)

Arduino installs it's own jre in C:\Program Files (x86)\Arduino\java\ and that cacerts file needs to be updated!

Kind of a shame that the currently shipping version has a jre with missing certs needed to download the board packages.

**Comment by NeMeSiS97** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3
> I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
> I tried a fresh install of the Arduino IDE
> I tried resetting my PPPoE Connection via my modem to my ISP
> I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
> None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

This is indeed the correct solution.
Thanks alot mate

**Comment by iofirag** [comment]
open arduino ide
File > Preferences

copy paste to the input box of (Additional boards manager urls):
https://arduino.esp8266.com/stable/package_esp8266com_index.json

click on arduino folder url link at the bottom. and leave it aside.

click ok in preferences screen.

open cmd and copy paste this:
"setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"

open ide again, and wait a minute.
looking on the content folder from before, when something has changed,
wait some seconds to finish, 
and then, 
delete all from the folder except from the preferences.txt

open:
Tools > Board > Board Manager

see if the loader in the bottom finish working

**Comment by smtpsantiago** [comment]
They recommend deleting the file package_index.json that is stored in package_index.json or package_index.json.tmp

**Comment by JeffrySan** [comment]
I had this issue - I am running Windows 10, Arduino IDE 1.8.3
I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true"
I tried a fresh install of the Arduino IDE
I tried resetting my PPPoE Connection via my modem to my ISP
I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot
I tried by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and delete all of them and nothing happend
None of these fixed the problem.

but when i try to uninstall java and reinstall it and plus to configure java path on Advance System Settings, it's good (in condition i reinstall arduino, i delete file in arduino>file>preferences folder)

Goodluck guyss

**Comment by pvinod424** [comment]
It worked for me!! Try this definately
I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"

**Comment by Ksol13** [comment]
I have the same problem.
But if i try to delete "package_index.json.tmp", a new file comes up again and again.
Whats my mistake?

**Comment by JeffrySan** [comment]
Re Install your Java from computer :
1. Uninstall java from (add remove program (search))
2. Install Java from https://www.java.com/en/download/

**Comment by MiracelVip** [comment]
I have the same problem here... my computer is connected to an IPv6 DSLITE internet. I cant open the "https://downloads.arduino.cc/libraries/library_index.json.sig" it says "not found" the only posibility was to open a hotspot with my mobile and download the file

It seems like a ipv4 ipv6 problem

**Comment by yihanglim** [comment]
> I have the same problem.
> But if i try to delete "package_index.json.tmp", a new file comes up again and again.
> Whats my mistake?

Same here, tried all method stated above, the file just keep comes up again when try to open board manager. Are you able to solve it yet?

**Comment by ptrooms** [comment]
I've perhaps a related problem.
When I try to use Board_manager, I run into an java.lang.RuntimeException: 
```
java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$1(ContributionManagerUI.java:150)
        at java.lang.Thread.run(Thread.java:748)
```
After this, Arduino cannot be restarted as long the "package_index.json" exists. 
Removing this re-iterates the problem as soon as I (need to) update board manager.

Note: I run Linux, the problem initiated on Arduino 18.5 and persists with the latest 1.8.12. The same happens on a clean  machine. Hence, something is wrong with "package_index.json"

**Comment by KTibow** [comment]
You could try deleting all files that seem related to `package_index.json`, not just `package_index.json.tmp`.

**Comment by ptrooms** [comment]
@KTibow : same result. Clearing the .Arduino15 directory will refill it with newly downloaded files as soon when I try to use BoardManager.

**Comment by yihanglim** [comment]
@ptrooms after spending whole night of troubleshooting, I couldn't find a solution. This version used to work fine for a few days before and suddenly this issue occurred out of nothing. So I uninstalled 1.8.12 and installed the hourly builds (last upated 3 June 2020 22:13:17 GMT) . So far everything runs alright.

**Comment by ptrooms** [comment]
@yihanglim , yes metoo. Currently I'm using the nightly version also. See the other threads for more details. Time for a good nap of sleep.

**Comment by facchinm** [comment]
We had a problem on our package_index.json that caused the error and prevented the IDE to start.
Now the package_index has been fixed, but to recover a working installation you must delete once again the package_index.json with the cache folder and restart the IDE as usual.

Windows:
* remove file C:\Users\YourUsername\AppData\Local\Arduino15\package_index.json
* remove folder C:\Users\YourUsername\AppData\Local\Arduino15\cache

Mac:
* remove file /Users/YourUsername/Library/Arduino15/package_index.json
* remove folder /Users/YourUsername/Library/Arduino15/cache

Linux:
* remove file /home/YourUsername/.arduino15/package_index.json
* remove folder /home/YourUsername/.arduino15/cache

Please note that the problem that prevents the IDE to start has already been fixed and it's ready for the next release, that's the reason why the Nightly/Beta Builds are not affected, and also the reason why we did not detect this problem earlier, sorry about that!

**Comment by dharmik768** [comment]
Tried everything and at last, @ShotgunBurger fixed my bug thanks man.

**Comment by dammyjay** [comment]
> > I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> This one worked for me also.... Thanks Much...

so reliefed

**Comment by bunya017** [comment]
If everything here doesn't work for you, download the package manually and place it in `C:\Users\< USER >\AppData\Local\Arduino15\staging\packages`. Then go back to the IDE and install again.

**Comment by behnamsaberi** [comment]
> I had this issue - I am running Windows 10, Arduino IDE 1.8.3 I tried the CMD Prompt "setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true" I tried a fresh install of the Arduino IDE I tried resetting my PPPoE Connection via my modem to my ISP I tried using WiFi, Ethernet and tethering to my cell phone's ISP via personal hotspot None of these fixed the problem.
> 
> I fixed my issue by going to "ThisPC>(C:)>Users>xxxx>AppData>Local>Arduino15" and deleting the file "package_index.json.tmp"
> 
> Now it works fine.

hi , it worked for me too
thanksssss
