### ISSUE TITLE
install.sh only creates a shortcut, doesn't actually install the IDE

### ISSUE THREAD

**Issue by ThellraAK** [arduino/Arduino#5366]
I was trying to get arduino working from the terminal when I realized 

trying to call arduino from terminal only resulted in a message saying it isn't currently installed
```
~/arduino-1.6.11⟫ arduino
The program 'arduino' is currently not installed. You can install it by typing:
sudo apt install arduino
```

When you do it with ./ it works (other than the problem with X stuff)
```
~/arduino-1.6.11⟫ ./arduino
Picked up JAVA_TOOL_OPTIONS: 
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
        at processing.app.Base.<clinit>(Base.java:92)`
```
Even when I ran the install script
```
~/arduino-1.6.11⟫ sudo ./install.sh
Adding desktop shortcut, menu item and file associations for Arduino IDE... done!
```
```
~/arduino-1.6.11⟫ arduino
The program 'arduino' is currently not installed. You can install it by typing:
sudo apt install arduino
```

I also did this without the sudo and got the same results.

The workaround I found is adding the ./ into the script provided by [this manpage](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc)
```bash
#!/bin/bash
Xvfb :1 -nolisten tcp -screen :1 1280x800x24 &
xvfb="$!"
DISPLAY=:1 ./arduino "$@"
kill -9 $xvfb`
```

**Comment by facchinm** [comment]
Fixed by #7593
