### ISSUE TITLE
Arduino 1.6.12 NullPointerException on startup

### ISSUE THREAD

**Issue by luii** [arduino/Arduino#5669]
Right after i type `arduino` into the terminal i get following `NullPointerException`
Im on Arch Linux and i've also removed and reinstalled arduino couple of time
The current devkit im using is 7
```bash
# luii at arch in ~ [18:48:18]
→ archlinux-java status
Available Java environments:
  java-7-openjdk/jre (default)
  java-8-openjdk
```

```bash
# luii at arch in ~ [18:46:12]
→ arduino                  
Picked up JAVA_TOOL_OPTIONS: 
java.lang.NullPointerException
	at cc.arduino.contributions.packages.ContributionsIndexer.getContributedPlaform(ContributionsIndexer.java:472)
	at processing.app.BaseNoGui.getBoardPreferences(BaseNoGui.java:168)
	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:804)
	at processing.app.Base.onBoardOrPortChange(Base.java:1301)
	at processing.app.Base$12.actionPerformed(Base.java:1524)
	at processing.app.Base.filterVisibilityOfSubsequentBoardMenus(Base.java:1563)
	at processing.app.Base.access$000(Base.java:81)
	at processing.app.Base$11.actionPerformed(Base.java:1496)
	at processing.app.Base.rebuildBoardsMenu(Base.java:1474)
	at processing.app.Base.<init>(Base.java:294)
	at processing.app.Base.guardedMain(Base.java:219)
	at processing.app.Base.main(Base.java:132)
```

**Comment by luii** [comment]
Okay i got it back working again.
Recently i installed some boards from SparkFun to the IDE, after i deleted them it was back to normal.
