### ISSUE TITLE
Arduino IDE won't communicate with Arduino Board

### ISSUE THREAD

**Issue by kd7sjt** [arduino/Arduino#5693]
Greetings,

I am using an Arduino Uno. I am using Linux Mint 18 and the stock Arduino IDE from the Repo. It is version 1.0.5. I did a complete update of everything on my machine using the command: apt update and apt dist-upgrade. That brought down all updates and the latest Kernel. My kernel version is 4.4.0-53.74.

With that update, I can no longer upload to my arduino. The error it gives me is:
"processing.app.SerialNotFoundException: Serial port '/dev/ttyACM0' not found. Did you select the right one from the Tools > Serial Port menu?
	at processing.app.Serial.<init>(Serial.java:191)
	at processing.app.Serial.<init>(Serial.java:77)
	at processing.app.debug.Uploader.flushSerialBuffer(Uploader.java:77)
	at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:175)
	at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:67)
	at processing.app.Sketch.upload(Sketch.java:1671)
	at processing.app.Sketch.exportApplet(Sketch.java:1627)
	at processing.app.Sketch.exportApplet(Sketch.java:1599)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2380)
	at java.lang.Thread.run(Thread.java:745)"

The Port selection is "Greyed" out also, so I am not able to select a port at all.

I don't know what to do. I did a search for this issue on this forum but didn't find anything remotely close to it. I think I put all the info down here, but if you need further info please drop me an email and I will furnish it for you. Thank you.

**Comment by facchinm** [comment]
Hi @kd7sjt, version 1.0.7 is ancient so some incompatibility with modern distros is expected. You'd better download the latest mainline from https://www.arduino.cc/en/Main/Software; if it doesn't solve your issue, try googling for workarounds on Linux. Probably the problem you are encountering is related with permissions, so adding your user to `tty` or `plugdev` or `uucp` groups (the exact group depends on your distro) should do the trick :slightly_smiling_face:
