### ISSUE TITLE
IDE won't start after installing a library with an invalid version

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#7917]
Using Arduino IDE 1.8.6/Arduino IDE 1.8.6 Hourly Build 2018-08-23 11:33/Arduino 1.9.0-beta build 80 on Windows 10 64 bit

When a library is installed with an invalid value in its library.properties `version` field the Arduino IDE will not start.

1. Download [xbee_serial_array-master.zip](https://github.com/arduino/Arduino/files/2316802/xbee_serial_array-master.zip)
1. Sketch > Include Library > Add .ZIP Library... > select the downloaded file > Open
1. File > Quit
1. Attempt to run the Arduino IDE - It does not start.

arduino_debug.exe output:
```
C:\ArduinoIDE\arduino-1.8.6>arduino_debug.exe
Loading configuration...
Initializing packages...
Preparing boards...
Invalid version found: 0.9a
java.lang.NullPointerException
        at processing.app.packages.UserLibrary.create(UserLibrary.java:156)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanLibrary(LibrariesIndexer.java:213)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanInstalledLibraries(LibrariesIndexer.java:190)
        at cc.arduino.contributions.libraries.LibrariesIndexer.rescanLibraries(LibrariesIndexer.java:150)
        at cc.arduino.contributions.libraries.LibrariesIndexer.setLibrariesFolders(LibrariesIndexer.java:109)
        at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:677)
        at processing.app.Base.onBoardOrPortChange(Base.java:1313)
        at processing.app.Base$11.actionPerformed(Base.java:1514)
        at processing.app.Base.rebuildBoardsMenu(Base.java:1490)
        at processing.app.Base.<init>(Base.java:267)
        at processing.app.Base.main(Base.java:145)
```
The problem does not occur with Arduino IDE 1.8.5.

**Comment by PaulStoffregen** [comment]
Didn't see this last night & made a redundant fix.

https://github.com/arduino/Arduino/pull/7922 is simpler, but doesn't address some of the stuff in https://github.com/arduino/Arduino/pull/7920 like better error messages libs without any .h file.
