### ISSUE TITLE
Open a .pde that starts with a number produces a Java ArrayIndexOutOfBounds exception [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#798]
This is [Issue 798](http://code.google.com/p/arduino/issues/detail?id=798) moved from a Google Code project.
Added by 2012-01-21T18:35:33.000Z by [gorth...@gmail.com](http://code.google.com/u/114458760365136703821/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Create a simple "pde" file that starts with a number. In my case I had downloaded one called "6502emu2.pde"
2. Attempt to open the pde file using File->Open
3. Dialog appears: "The file "6502emu2.pde" needs to be inside a sketch folder named "6502emu2". Create this folder, move the file, and continue?"
4. Click OK

**What is the expected output? What do you see instead?**

Arduino software creates the folder, moves the file, but then throws an ArrayIndexOutOfBounds exception, and dumps out the following stack trace:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at processing.app.Sketch.setCurrentCode(Sketch.java:1159)
	at processing.app.Sketch.load(Sketch.java:219)
	at processing.app.Sketch.<init>(Sketch.java:141)
	at processing.app.Editor.handleOpenInternal(Editor.java:2132)
	at processing.app.Editor.<init>(Editor.java:311)
	at processing.app.Base.handleOpen(Base.java:700)
	at processing.app.Base.handleOpen(Base.java:665)
	at processing.app.Base.handleOpenPrompt(Base.java:654)
	at processing.app.Editor$5.actionPerformed(Editor.java:503)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:95)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:627)
	at java.awt.MenuItem.processEvent(MenuItem.java:586)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:337)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:325)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:682)
	at java.awt.EventQueue.access$000(EventQueue.java:85)
	at java.awt.EventQueue$1.run(EventQueue.java:638)
	at java.awt.EventQueue$1.run(EventQueue.java:636)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
	at java.awt.EventQueue$2.run(EventQueue.java:652)
	at java.awt.EventQueue$2.run(EventQueue.java:650)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:649)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0, on MacOS X (Intel 64-bit), 10.7.2.
Using an Arduino Uno board (board doesn't need to be connected)

**Please provide any additional information below.**

If you add a letter in front of the name, then File->Open works correctly - it creates the folder, moves the file, and then opens it up in the Editor.

Obviously, this is "user error" since my file didn't start with a letter, but it should probably not throw an exception and should gracefully fail.

Thanks!

**Comment by ffissore** [comment]
Invalid sketch names are filtered and the exception is not thrown any more

**Comment by chris-torrence** [comment]
Thanks for fixing!
