### ISSUE TITLE
IDE does not launch Ubuntu 18.10

### ISSUE THREAD

**Issue by danieleperot** [arduino/Arduino#8119]
I downloaded the new IDE 1.8.7 for Linux x64.
I am using the Oracle version of JDK and JRE.
While trying to lunch the IDE, i got the following error:

```
Picked up JAVA_TOOL_OPTIONS: 
java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1351)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getLookAndFeel(UIManager.java:492)
	at processing.app.linux.GTKLookAndFeelFixer.installGtkPopupBugWorkaround(GTKLookAndFeelFixer.java:79)
	at processing.app.linux.Platform.setLookAndFeel(Platform.java:44)
	at processing.app.Base.<init>(Base.java:239)
	at processing.app.Base.main(Base.java:145)
```

I got it fixed by changing line 28 in the arduino script from:

```
JAVA_OPTIONS=("-DAPP_DIR=$APPDIR" "-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
```
to
```
JAVA_OPTIONS=("-DAPP_DIR=$APPDIR")
```
I hope this can help somebody with the same problem I had!

**Comment by facchinm** [comment]
Hi @danieleperot ,
thanks for reporting! Are you using any particular flavour of Ubuntu or is it the plain image?

**Comment by facchinm** [comment]
I've been able to reproduce it with a clean 18.10 installation. The problem is related with 18.10 shipping without `libgtk2.0` installed by default; I'm pushing a workaround soon.

**Comment by danieleperot** [comment]
I can confirm that installing libgtk2.0 does fix the issue.
Thank you very much!
