### ISSUE TITLE
java.lang.IllegalStateException when canceling [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#850]
This is [Issue 850](http://code.google.com/p/arduino/issues/detail?id=850) moved from a Google Code project.
Added by 2012-03-07T18:44:53.000Z by [lars.j.nielsen@gmail.com](http://code.google.com/u/lars.j.nielsen@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.Start IDE.
2. Write anything in the sketch.
3. Try to close the IDE, press escape or cancel when asked if you want to save first.

**What is the expected output? What do you see instead?**

Expected result:
Nothing noticeable other than the popup disappearing.

Actual result:
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException
	at processing.app.Editor.checkModified(Editor.java:1973)
	at processing.app.Base.handleClose(Base.java:753)
	at processing.app.Editor$1.windowClosing(Editor.java:163)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:332)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:332)
	at java.awt.Window.processWindowEvent(Window.java:1862)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:279)
	at java.awt.Window.processEvent(Window.java:1820)
	at java.awt.Component.dispatchEventImpl(Component.java:4630)
	at java.awt.Container.dispatchEventImpl(Container.java:2099)
	at java.awt.Window.dispatchEventImpl(Window.java:2475)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
1.0.
Windows 7.
Uno.

**Please provide any additional information below.**
Can't reproduce on another machine. Might be a question of java versions. Right now I don't have access to the one I had the issue on, but the one I can't reproduce it on is:

java version "1.7.0"
Java(TM) SE Runtime Environment (build 1.7.0-b147)
Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)

I'll add the java info from the one I had the issue on tomorrow.

**Comment by ffissore** [comment]
Can't reproduce. I guess this has been fixed a long time ago
