### ISSUE TITLE
Cannot start Arduino

### ISSUE THREAD

**Issue by toomasz** [arduino/Arduino#8986]
Hi, i'm unable to start arduino. Tried both 1.8.9 and beta versions.

```Microsoft Windows [Version 10.0.17134.829]
(c) 2018 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Program Files (x86)\Arduino>arduino_debug
Ładowanie konfiguracji...
Inicjowanie pakietów...
Przygotowywanie płytek
java.lang.NullPointerException
        at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:732)
        at processing.app.Base.onBoardOrPortChange(Base.java:1402)
        at processing.app.Base$12.actionPerformed(Base.java:1648)
        at processing.app.Base.rebuildBoardsMenu(Base.java:1585)
        at processing.app.Base.<init>(Base.java:282)
        at processing.app.Base.main(Base.java:158)

C:\Program Files (x86)\Arduino>```

**Comment by facchinm** [comment]
Hi @toomasz ,
the line that is provoking the crash is likely https://github.com/arduino/Arduino/blob/1.8.9/arduino-core/src/processing/app/BaseNoGui.java#L732 . 

My debugging advice would be:
* in your sketchbook folder (normally `C:\Users\yourusername\Arduino`) rename `libraries` directory to `libraries.bak` and try starting the IDE. 
* If it succeeds, try copying the libraries from `libraries.bak` to  `libraries` until it breaks. 

I'd be glad if you could also send us the library that provokes this error so we can duplicate the crash, thanks!
