### ISSUE TITLE
WiFi 101 Firmware updater - updater sketch doesn't open on macOS 10.14/10.15

### ISSUE THREAD

**Issue by gvarisco** [arduino/Arduino#9293]
I've noticed the Updater sketch doesn't work as expected when clicked. Tested on both macOS 10.14 and 10.15, IDE 1.8.10.
 
<img width="494" alt="Screenshot 2019-10-07 at 17 30 37" src="https://user-images.githubusercontent.com/945486/66325839-3c3b6580-e928-11e9-947d-6af972bb7461.png">

When 'Open Updater Sketch' is clicked, a NPE gets logged in the console:

> java.lang.NullPointerException
	at cc.arduino.plugins.wifi101.UpdaterImpl.openFirmwareUpdaterSketch(UpdaterImpl.java:190)
	at cc.arduino.plugins.wifi101.UpdaterJFrame$5.actionPerformed(UpdaterJFrame.java:182)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by gvarisco** [comment]
OK, once libs are installed it works. Maybe we shall notify the user somehow.

**Comment by aubergene** [comment]
How do I install the libs?

**Comment by gvarisco** [comment]
@aubergene Tools -> Manage Libraries...

Then install 'WifiNINA' and/or 'Wifi101' libraries.

**Comment by facchinm** [comment]
Moved to https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/issues/45
