### ISSUE TITLE
Java exceptions + Sketch uses 3160 bytes, maximum is 253952 bytes. ???

### ISSUE THREAD

**Issue by chrissound** [arduino/Arduino#9481]
Sorry not sure what other info I could provide. This file/code works correctly via the IDE but not the command line:

```
arduino --verify x.ino        
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
[JmDNS(fe80-0-0-0-643f-59ff-fed4-10c5-ve-nixbincache.local.).Timer] WARN javax.jmdns.impl.tasks.resolver.DNSResolverTask - ServiceResolver(fe80-0-0-0-643f-59ff-fed4-10c5-ve-nixbincache.local.).run() exception 
[JmDNS(2a02-c7f-7066-c400-6670-2ff-fe26-d88-wlp2s0f0u7.local.).Timer] WARN javax.jmdns.impl.tasks.resolver.DNSResolverTask - ServiceResolver(2a02-c7f-7066-c400-6670-2ff-fe26-d88-wlp2s0f0u7.local.).run() exception 
[JmDNS(fd41-931f-1a76-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).Timer] WARN javax.jmdns.impl.tasks.resolver.DNSResolverTask - ServiceResolver(fd41-931f-1a76-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).run() exception 
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[fe80-0-0-0-643f-59ff-fed4-10c5-ve-nixbincache.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[fd41-931f-1a76-0-6670-2ff-fe26-d88-wlp2s0f0u7.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[JmDNS(fe80-0-0-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).Timer] WARN javax.jmdns.impl.tasks.resolver.DNSResolverTask - ServiceResolver(fe80-0-0-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).run() exception 
[JmDNS(fc00-0-0-0-0-0-0-1-ve-nixbincache.local.).Timer] WARN javax.jmdns.impl.tasks.resolver.DNSResolverTask - ServiceResolver(fc00-0-0-0-0-0-0-1-ve-nixbincache.local.).run() exception 
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[2a02-c7f-7066-c400-6670-2ff-fe26-d88-wlp2s0f0u7.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[fe80-0-0-0-6670-2ff-fe26-d88-wlp2s0f0u7.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[fc00-0-0-0-0-0-0-1-ve-nixbincache.local..recover()] WARN javax.jmdns.impl.JmDNSImpl - RECOVERING
[JmDNS(fe80-0-0-0-643f-59ff-fed4-10c5-ve-nixbincache.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(fe80-0-0-0-643f-59ff-fed4-10c5-ve-nixbincache.local.).run() exception 
[JmDNS(fe80-0-0-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(fe80-0-0-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).run() exception 
[JmDNS(fc00-0-0-0-0-0-0-1-ve-nixbincache.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(fc00-0-0-0-0-0-0-1-ve-nixbincache.local.).run() exception 
[JmDNS(fd41-931f-1a76-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(fd41-931f-1a76-0-6670-2ff-fe26-d88-wlp2s0f0u7.local.).run() exception 
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[JmDNS(2a02-c7f-7066-c400-6670-2ff-fe26-d88-wlp2s0f0u7.local.).State.Timer] WARN javax.jmdns.impl.tasks.state.DNSStateTask - Canceler(2a02-c7f-7066-c400-6670-2ff-fe26-d88-wlp2s0f0u7.local.).run() exception 
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
java.io.IOException: Cannot assign requested address (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1618)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Sketch uses 3160 bytes (1%) of program storage space. Maximum is 253952 bytes.
Global variables use 13 bytes (0%) of dynamic memory, leaving 8179 bytes for local variables. Maximum is 8192 bytes.

```

**Comment by facchinm** [comment]
@chrissound the `JmDNS` exceptions are only related with network discovery and upload, you just see them because launching the IDE from a terminal makes them visible.
Your sketch is compiling fine, but you are probably missing the `--board` parameter (see https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc#synopsis)
